### ISSUE TITLE
Generify the Dist Generator

### ISSUE THREAD

**Issue by jd-carroll** [FamousTools/famous-dist-generator#11]
I am going to start working on generifing the dist generator to work for any repository.  I have several components where I would like to create Angular directives (Scrollview replacement).  However, the components are written with the same AMD format as the core Famous library so I will need to package the code in a similar format as the famous global.

Right now the focus will be on the following items:
- Add properties file support
- Merge command line args and properties file
- Pass reference to `config` object for all settings

**If anyone else has any ideas or things they would like to see, please let me know.**

**Comment by TheAlphaNerd** [comment]
Hey jd-caroll.

Thanks for all the work today.  I’m going to take a peak at merging things in tomorrow.

Fwiw I have already started work on making things a bit more generic by breaking out features of this tool into generic modules

https://github.com/TheAlphaNerd/common-ground ~ Strip off AMD
https://github.com/TheAlphaNerd/index-finger ~ Generate index

Let me know where you are thinking of taking this… we definitely are open to rewriting the dist-generator, specifically to refactor out the git-cache and simplify the logic.

**Comment by jd-carroll** [comment]
Cool, I'll definitely take a look at those projects.  I have to admit I'm not 100% up on what is happening in the git-cache so I'll have to spend a little time there first.

For right now, I am focused on a specific use case (being able to use the dist generator for my project).  Once I have that working, I will try to take a larger view of the code and see where we can take it.  I'm a little concerned about what will have to happen to get this working because I need to make sure that the final result will transform all of my `require('famous/core/...')`'s into `famous.core. ...` or something similarly appropriate.  

I'm not certain how requirejs will handle this and if I need to go in and start doing that conversion manually it could get a little scarry.  But I don't know, it could be that requirejs handles this out of the box and I have nothing to worry about.

**Comment by TheAlphaNerd** [comment]
Hey jd-caroll.

I just finished updating the dist generator to v1.0.x, it was a complete rewrite.  It is not exactly "generic" yet, but it is pretty close.  Feel free to take a peek and make whatever changes are neccessary
