### ISSUE TITLE
Convert windows path separators to UNIX separators

### ISSUE THREAD

**Issue by jd-carroll** [FamousTools/famous-dist-generator#8]
When sending the list of modules to the requirejs optimizer, we do not normalize the paths for UNIX separators.  This causes the requirejs engine to fail because it looks for <relative_path>\\some\\folder.

Part of fix for #4 

jrburke/requirejs#1262

**Comment by TheAlphaNerd** [comment]
no longer an issue with v1.0.x of dist-generator

:smile:
